apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  type: NodePort
  selector:
    app: calculator
  ports:
    - protocol: TCP
      port: 8080         # External service port
      targetPort: 8080 # Internal pod port used by Spring Boot
      nodePort: 30080  # Node port for external access
